ent/contrib

- entgql/internal/todopulid/ent/runtime.go
- entgql/internal/todopulid/ent/schema/todo.go
> examples/pulid: reuse base todo schema

- schemast/annotation.go
- schemast/astutil.go
- schemast/edge.go
- schemast/edge_test.go
- schemast/field.go
- schemast/field_test.go
- schemast/index.go
- schemast/index_test.go
- schemast/internal/mutatetest/ent/schema/withfields.go
- schemast/kind.go
- schemast/load.go
- schemast/load_test.go
- schemast/mutate.go
- schemast/mutate_test.go
- schemast/printer_test.go
- schemast/type.go
also: DRYing up the append returned item AST code.
> schemast: support adding returned items to non-existing methods.

- schemast/field.go
- schemast/field_test.go
> schemast: basic support for default values for fields

- schemast/field.go
- schemast/field_test.go
> schemast: support field.Time

- entproto/README.md
Update entproto's README.md to reflect changes caused by https://github.com/ent/contrib/pull/158
> entproto: document service method generation options

- entproto/README.md
- entproto/internal/entprototest/ent/schema/all_methods_service.go
- entproto/internal/entprototest/ent/schema/one_method_service.go
- entproto/internal/entprototest/ent/schema/two_method_service.go
- entproto/internal/todo/ent/schema/nil_example.go
cc @JeremyV2014 - looks nicer this way IMO.
> entproto: rm uneeded nesting for entproto.Methods args

- entoas/annotation.go
- entoas/edges.go
can reintroduce max depth any time later if some user needs it.
cc @a8m
> entoas: replace depth logic

- schemast/astutil.go
- schemast/field.go
- schemast/field_test.go
- schemast/mutate.go
- schemast/printer_test.go
Adding support for generating UUID fields.
cc @a8m
> Add support for UUID fields.

- entoas/generator.go
- entoas/internal/cycle/openapi.json
- entoas/internal/pets/openapi.json
> entoas: remove sub-resource filter for implementing packages

- entgql/internal/todoplugin/ent/category.go
- entgql/internal/todoplugin/ent/category/category.go
- entgql/internal/todoplugin/ent/category/where.go
- entgql/internal/todoplugin/ent/category_create.go
- entgql/internal/todoplugin/ent/category_update.go
- entgql/internal/todoplugin/ent/gql_node.go
- entgql/internal/todoplugin/ent/migrate/schema.go
- entgql/internal/todoplugin/ent/mutation.go
- entgql/internal/todoplugin/ent/schema/category.go
- entgql/internal/todoplugin/generated.go
- entgql/internal/todoplugin/todo_test.go
- entgql/schema.go
- entgql/schema_test.go
Included: Ints(), Floats(), Strings()
> entgql: support builtin JSON types

- entgql/internal/todoplugin/generated.go
- entgql/internal/todoplugin/todo.graphql
- entgql/schema.go
- entgql/schema_relay.go
Related: https://github.com/ent/ent/issues/2351
> entgql: add OrderDirection to builtin types

- entgql/internal/todo/ent/gql_collection.go
- entgql/internal/todo/ent/gql_edge.go
- entgql/internal/todo/ent/gql_pagination.go
- entgql/internal/todo/ent/schema/todo.go
- entgql/internal/todo/generated.go
- entgql/internal/todo/todo.graphql
- entgql/internal/todo/todo_test.go
- entgql/internal/todofed/ent/gql_pagination.go
- entgql/internal/todoplugin/ent/gql_collection.go
- entgql/internal/todoplugin/ent/gql_edge.go
- entgql/internal/todoplugin/ent/gql_pagination.go
- entgql/internal/todoplugin/ent/schema/todo.go
- entgql/internal/todoplugin/generated.go
- entgql/internal/todoplugin/todo.graphql
- entgql/internal/todoplugin/todo_test.go
- entgql/internal/todopulid/ent/gql_collection.go
- entgql/internal/todopulid/ent/gql_edge.go
- entgql/internal/todopulid/ent/gql_pagination.go
- entgql/internal/todopulid/generated.go
- entgql/internal/todouuid/ent/gql_collection.go
- entgql/internal/todouuid/ent/gql_edge.go
- entgql/internal/todouuid/ent/gql_pagination.go
- entgql/internal/todouuid/generated.go
- entgql/plugin.go
- entgql/schema.go
- entgql/schema_test.go
- entgql/template.go
- entgql/template/pagination.tmpl
Related to this comment: https://github.com/ent/ent/issues/2351#issuecomment-1057135721
> entgql: generate edge fields

- entgql/annotation.go
- entgql/extension.go
- entgql/internal/todoplugin/ent/schema/todo.go
- entgql/internal/todoplugin/entgql.resolvers.go
- entgql/internal/todoplugin/generated.go
- entgql/internal/todoplugin/todo.graphql
- entgql/internal/todoplugin/todo.resolvers.go
- entgql/schema.go
- entgql/schema_test.go
- entgql/template.go
- go.sum
Related issue: https://github.com/ent/ent/issues/2351
> entgql: expose the Entity connection on the Query type

- entgql/internal/todo/ent.resolvers.go
- entgql/internal/todo/ent/gql_where_input.go
- entgql/internal/todo/generated.go
- entgql/internal/todo/todo.graphql
- entgql/internal/todo/todo.resolvers.go
- entgql/internal/todo/todo_test.go
- entgql/internal/todoplugin/ent/gql_where_input.go
- entgql/internal/todopulid/ent.resolvers.go
- entgql/internal/todopulid/ent/gql_where_input.go
- entgql/internal/todopulid/generated.go
- entgql/internal/todopulid/todo.resolvers.go
- entgql/internal/todouuid/ent.resolvers.go
- entgql/internal/todouuid/ent/gql_where_input.go
- entgql/internal/todouuid/generated.go
- entgql/internal/todouuid/todo.resolvers.go
- entgql/template/where_input.tmpl
See [comment](https://github.com/ent/ent/issues/2351#issuecomment-1107518277) for more information.
The only real changes are:
https://github.com/ent/contrib/blob/c0c2a2d3b6fae82472234b30bd981803881076f6/entgql/template/where_input.tmpl#L35
and:
https://github.com/ent/contrib/blob/c0c2a2d3b6fae82472234b30bd981803881076f6/entgql/template/where_input.tmpl#L133
> entgql: adds support for custom predicates on where structs

- entproto/cmd/protoc-gen-entgrpc/main.go
- entproto/cmd/protoc-gen-entgrpc/template/method_batch_create.tmpl
- entproto/service.go
> entproto: use ent custom pluralizer

- go.mod
- go.sum
Closes https://github.com/ent/ent/issues/2878
> all: bump golang.org/x/tools

- entgql/internal/todo/ent/gql_edge.go
- entgql/internal/todo/todo_test.go
- entgql/internal/todofed/ent/gql_edge.go
- entgql/internal/todogotype/ent/gql_edge.go
- entgql/internal/todopulid/ent/gql_edge.go
- entgql/internal/todouuid/ent/gql_edge.go
- entgql/template/edge.tmpl
Related https://github.com/ent/ent/issues/2889
> entgql: fixed edge loading for non-relay field

- entgql/internal/todo/ent/gql_pagination.go
- entgql/internal/todofed/ent/gql_pagination.go
- entgql/internal/todogotype/ent/gql_pagination.go
- entgql/internal/todopulid/ent/gql_pagination.go
- entgql/internal/todouuid/ent/gql_pagination.go
- entgql/template/pagination.tmpl
Related to: https://github.com/ent/ent/issues/2984
> entgql: clone the query for `Count()`

- entgql/extension.go
Signed-off-by: Giau. Tran Minh <hello@giautm.dev>
> entgql: fix outputWriter non-order dependencies

- entgql/template/mutation_input.tmpl
See: https://github.com/golang/go/issues/30832\#issuecomment-472713264
Fixed https://github.com/ent/ent/issues/3176
> entgql: remove blank lines between imports

- entgql/internal/todopulid/ent/schema/pulid/pulid.go
Fixed: https://github.com/ent/ent/issues/3317
> entgql: fixed pulid example

- entgql/internal/todo/ent/gql_collection.go
- entgql/internal/todofed/ent/gql_collection.go
- entgql/internal/todogotype/ent/gql_collection.go
- entgql/internal/todopulid/ent/gql_collection.go
- entgql/internal/todouuid/ent/gql_collection.go
- entgql/template/collection.tmpl
collectField parameter named op, easy to conflict with the receiver such as (OrganizationPolicy -> op )
> change collectField parameter name

- entgql/template/enum.tmpl
Signed-off-by: Giau. Tran Minh <hello@giautm.dev>
> entgql: fixed enum import for graphql package

- entgql/internal/todo/ent/gql_collection.go
- entgql/internal/todo/todo_test.go
- entgql/internal/todofed/ent/gql_collection.go
- entgql/internal/todogotype/ent/gql_collection.go
- entgql/internal/todopulid/ent/gql_collection.go
- entgql/internal/todouuid/ent/gql_collection.go
- entgql/schema.go
- entgql/template.go
- entgql/template/collection.tmpl
- entgql: add support for query fields selection
- entgql: select edge's field on collect fields
> entgql: add support for query fields selection

- entgql/internal/todo/ent/gql_collection.go
- entgql/internal/todo/todo_test.go
- entgql/internal/todofed/ent/gql_collection.go
- entgql/internal/todogotype/ent/gql_collection.go
- entgql/internal/todopulid/ent/gql_collection.go
- entgql/internal/todouuid/ent/gql_collection.go
- entgql/template/collection.tmpl
This fixes a long time bug that was found now in the new fields selection optimization
> entgql: satisfies fragments on Node/Nodes queries

- entgql/internal/todo/ent/gql_collection.go
- entgql/internal/todo/todo_test.go
- entgql/internal/todofed/ent/gql_collection.go
- entgql/internal/todogotype/ent/gql_collection.go
- entgql/internal/todopulid/ent/gql_collection.go
- entgql/internal/todouuid/ent/gql_collection.go
- entgql/template/collection.tmpl
> entgql: fix field arguments collection

- entgql/internal/todo/ent/gql_pagination.go
- entgql/internal/todo/todo_test.go
- entgql/internal/todofed/ent/gql_pagination.go
- entgql/internal/todogotype/ent/gql_pagination.go
- entgql/internal/todopulid/ent/gql_pagination.go
- entgql/internal/todouuid/ent/gql_pagination.go
- entgql/template/pagination.tmpl
Related https://github.com/ent/ent/issues/2984
> entgql: fixed Paginate query for count
