ent/contrib

entproto/fieldmap.go, entproto/format.go, entproto/internal/entprototest/fieldmapper_test.go
used later in the gRPC codegen to easily describe the mapping between the ent.Schema fields and the proto desc.MessageDescriptor
=> entproto - adding FieldMap 

entgql/template.go
Export template funcs to that users can match the available functions in extensions
entgql_extensions.tmpl
```
{{ $gqlNodes := filterNodes $.Nodes }}
...
```
```go
var entgql_extensions = ...
gen.MustParse(gen.NewTemplate("entgql_extensions").
Funcs(entgql.TemplateFuncs).
Parse(entgql_extensions)),
```
=> Export TemplateFuncs

.github/dependabot.yml
Main repo already uses it, why does this one not? ent has had two releases already.
=> all: enable dependabot

entoas/annotation.go, entoas/annotation_test.go, entoas/generator.go, entoas/generator_test.go
This PR adds an Annotation to create an OAS type to use for custom GoTypes.
=> entoas: add annotation to support custom oas types

entoas/generator.go, entoas/internal/cycle/openapi.json, entoas/internal/oastypes/openapi.json, entoas/internal/pets/openapi.json, entoas/internal/simple/openapi.json
`ogen` just recently added the `Int()` spec-builder which is mapped to the Go `int` type. This PR uses the new `Int()` builder to not have `ogen` generate `int32` everywhere.
=> entoas: pagination params to Int instead of Int32

entoas/generator.go, entoas/internal/cycle/openapi.json, entoas/internal/pets/openapi.json, entoas/internal/simple/openapi.json
This PR adds a 404 response to the create operations on sub routes since the parent might not exist. Example: 
`POST /pets/1/owner` <- Pet with ID 1 might not exist. 404 is needed.
=> entoas: add 404 response to create-sub operation

entgql/internal/todo/ent/gql_where_input.go, entgql/internal/todopulid/ent/gql_where_input.go, entgql/internal/todouuid/ent/gql_where_input.go, entgql/template/where_input.tmpl
Let it be consistent with other error
=> fix: remove package name for the error

schemast/field.go, schemast/field_test.go
I was using entimport tool and was not able to generate schema files. Generating byte field was not supported for some reason. My column is defined as `BYTEA` in Postgres. After adding byte type to case switch entimport generated schema without problems
=> Added support to generate byte fields.

entgql/annotation.go, entgql/annotation_test.go, entgql/internal/todo/ent/schema/category.go, entgql/internal/todo/ent/schema/todo.go, entgql/internal/todofed/ent/gql_collection.go, entgql/internal/todofed/ent/schema/todo.go, entgql/template.go, entgql/template/collection.tmpl, entgql/template_test.go, go.sum
`Bind()` become a no-op function to avoid breaking the existing schema.
This commit also added `Unbind()` to disable bind.
=> entgql: enable bind by default

schemast/astutil.go, schemast/field.go, schemast/field_test.go, schemast/printer_test.go
Easiest implementation to support generating JSON fields I could think of.
Developers still need to change schema but at least generation does not fail
and generated file compiles.
=> Add support for generating JSON fields

entgql/template.go
Because in `gen.NewTemplate()` we already call `t.Funcs(Funcs)`
https://github.com/ent/ent/blob/a7beb5c834f0b81de7afd15350da9c42d8eb6b88/entc/gen/template.go#L231-L235
=> entgql: remove unnecessary `Funcs` call

entgql/internal/todoplugin/generated.go, entgql/schema.go, entgql/schema_models.go, entgql/schema_test.go
Next PR, will add support for mapping fields with custom GoType to `goModel`.
=> entgql: add goModel directive to generated enums

entoas/annotation.go, entoas/annotation_test.go, entoas/generator.go, entoas/internal/simple/category.go, entoas/internal/simple/category/category.go, entoas/internal/simple/category/where.go, entoas/internal/simple/category_create.go, entoas/internal/simple/category_update.go, entoas/internal/simple/migrate/schema.go, entoas/internal/simple/mutation.go, entoas/internal/simple/openapi.json, entoas/internal/simple/schema/category.go
Added FieldConfig struct to Annotation to support read only fields. Corresponding change coming to ogent that uses this flag to suppress parameter generation for read only fields (usefult for createdBy and createdAt fields).
=> added field annotation for read only flag

entgql/annotation.go, entgql/internal/todo/ent/gql_edge.go, entgql/internal/todopulid/ent/gql_edge.go, entgql/internal/todouuid/ent/gql_edge.go, entgql/schema.go, entgql/template.go, entgql/template/edge.tmpl, entgql/template/pagination.tmpl, go.mod, go.sum
If the target `Edge.Type` does not have order fields, they won't be defined in the GraphQL schema, and having them in the method signature will break the gqlgen binding.
=> entgql: move the order-fields logic to template function

entgql/annotation.go, entgql/annotation_test.go, entgql/extension.go, entgql/schema.go, entgql/schema_test.go, entgql/template.go, entgql/template/collection.tmpl, entgql/template/edge.tmpl, entgql/template/node.tmpl, entgql/template/pagination.tmpl, entgql/template/where_input.tmpl, entgql/template_test.go
Related to https://github.com/ent/ent/issues/2351#issuecomment-1057315202
=> entgql: refactor Skip annotation

schemast/field.go, schemast/field_test.go
ent is using `Float` and not `Float64` as the float64 field, this fix handles it.
```
// Float returns a new Field with type float64.
func Float(name string) *float64Builder {
return &float64Builder{&Descriptor{
Name: name,
Info: &TypeInfo{Type: TypeFloat64},
}}
}
```
=> schemast: proper float field conversion

entoas/annotation.go, entoas/annotation_test.go
The bug was due to using a copy instead of a reference
=> entoas: fix merge bug

entgql/annotation.go
I change the API to a chain, to be cleaner.
```go
entgql.QueryField().
Directives(entgql.Deprecated("we don't use this anymore")),
```
=> entgql: cleanup queryField annotation

entgql/internal/todo/ent/gql_collection.go, entgql/internal/todo/generated.go, entgql/internal/todo/todo_test.go, entgql/internal/todofed/ent/gql_collection.go, entgql/internal/todofed/generated.go, entgql/internal/todoplugin/ent/gql_collection.go, entgql/internal/todoplugin/generated.go, entgql/internal/todopulid/ent/gql_collection.go, entgql/internal/todopulid/generated.go, entgql/internal/todouuid/ent/gql_collection.go, entgql/internal/todouuid/generated.go, entgql/template/collection.tmpl, go.mod, go.sum
Related to https://github.com/ent/ent/issues/2351
=> entgql: Unmarshal whereInput using graphql package

entgql/internal/todo/ent/gql_node.go, entgql/internal/todofed/ent/gql_node.go, entgql/internal/todoplugin/ent/gql_node.go, entgql/internal/todopulid/ent/gql_node.go, entgql/internal/todouuid/ent/gql_node.go, entgql/template/node.tmpl
Hi, this is minor fix of example code in a comment.
Before fix, a example WithNodeType() receives a string.
Correct argument of the function is a function.
It was changed in below commit.
https://github.com/ent/contrib/commit/84ba3303a11cf67f0bd58e96d80cfa7bfc0600fb
However, the document has been updated.
https://entgo.io/docs/graphql/#node-api
=> entgql: fix example code in comment

entgql/extension.go
The naming is based on this comment: https://github.com/ent/contrib/blob/1faab982b6648b7704a6cf41ff65d9cb7811a2be/entgql/schema.go#L45
=> entgql: add WithRelaySpec to be able to disable Relay specification

entgql/internal/todo/ent/gql_where_input.go, entgql/internal/todo/todo_test.go, entgql/internal/todogotype/ent/gql_where_input.go, entgql/internal/todopulid/ent/gql_where_input.go, entgql/internal/todouuid/ent/gql_where_input.go, entgql/template/where_input.tmpl
Passing empty `not`, `and`, etc is invalid.
=> entgql: skip empty top-level where inputs

entgql/internal/todo/ent/gql_edge.go, entgql/internal/todo/todo_test.go, entgql/internal/todogotype/ent/gql_edge.go, entgql/internal/todopulid/ent/gql_edge.go, entgql/internal/todouuid/ent/gql_edge.go, entgql/template/edge.tmpl
Thanks @amrnt for reporting and provide the test cases, ❤️
=> entgql: fixed edge filter

entgql/internal/todo/ent/gql_collection.go, entgql/internal/todo/todo_test.go, entgql/internal/todofed/ent/gql_collection.go, entgql/internal/todogotype/ent/gql_collection.go, entgql/internal/todopulid/ent/gql_collection.go, entgql/internal/todouuid/ent/gql_collection.go, entgql/template/collection.tmpl
Fixed
```sh
interface conversion: interface {} is **ent.Cursor, not *ent.Cursor
```
=> entgql: fixed cursor type in nested pagination

entgql/template/enum.tmpl
Fixes https://github.com/ent/ent/issues/2517
Changes the interface check from trying to instantiate a string enum to checking the nil pointer type.
=> entgql: Use nil to check that a generated enum satisfies interface 

entgql/annotation.go, entgql/annotation_test.go, entgql/internal/todo/ent.graphql, entgql/internal/todo/ent/schema/annotation/has_permissions.go, entgql/internal/todo/ent/schema/group.go, entgql/internal/todo/generated.go, entgql/internal/todo/has_permission.go, entgql/internal/todo/resolver.go, entgql/internal/todo/todo.graphql, entgql/internal/todogotype/generated.go, entgql/internal/todogotype/resolver.go, entgql/internal/todopulid/generated.go, entgql/internal/todopulid/resolver.go, entgql/internal/todouuid/generated.go, entgql/schema.go, entgql/schema_test.go
Hi 👋 That's my first time contributing to `Ent` and I must say I'm enjoying it so far.
This PR allows the creation of a directive annotation using a child value list, for example:
```
directive @hasPermissions(permissions: [String!]!) on OBJECT | FIELD_DEFINITION
```
The original implementation only allowed the user to specify a `string` as a value:
https://github.com/ent/contrib/blob/462c4e5698731377eb38f5a61b16518bb7295341/entgql/annotation.go#L61-L65
https://github.com/ent/contrib/blob/462c4e5698731377eb38f5a61b16518bb7295341/entgql/annotation.go#L518-L528
Now you can specify a child value list:
```golang
func HasPermissions(permissions []string) entgql.Directive {
return entgql.NewDirective("hasPermissions", entgql.DirectiveArgument{
Name:     "permissions",
Kind:     ast.ListValue, …
```
=> feat(entgql): support child value list for directive annotation

entgql/internal/todo/ent/gql_edge.go, entgql/internal/todofed/ent/gql_edge.go, entgql/internal/todogotype/ent/gql_edge.go, entgql/internal/todopulid/ent/gql_edge.go, entgql/internal/todouuid/ent/gql_edge.go, entgql/template/edge.tmpl, go.mod, go.sum
In case the context is non-gql, we fllback to the regular eager-loading flow (i.e. With<E>)
=> entgql: accept non-gql context in generated edge methods

entoas/extension.go, entoas/extension_test.go, entoas/generator.go, entoas/internal/cycle/openapi.json, entoas/internal/oastypes/openapi.json, entoas/internal/pets/openapi.json, entoas/internal/simple/openapi.json
Ensures the `itemsPerPage` parameter is at least 1 and less than 255. Added the `MinItemsPerPage()` and `MaxItemsPerPage()` options for configuration.
=> entoas: add boundaries for `page` and `itemsPerPage` pagination params

schemast/field.go, schemast/field_test.go, schemast/mutate.go
* Support custom structs for JSON Fields
* Add Args to the base call instead of the final one
* Append any necessary imports for the struct
=> schemast: fix support for generating JSON fields (#3005)

entgql/internal/todo/ent/gql_pagination.go, entgql/internal/todo/ent/schema/group.go, entgql/internal/todopulid/ent/gql_pagination.go, entgql/internal/todouuid/ent/gql_pagination.go, entgql/template/pagination.tmpl
I think the multi order template was tested on category so `c` was hard coded.
I fix the template as well as added the annotation to `Group`.
=> fix multiOrder template

entgql/template/where_input.tmpl
Fixes https://github.com/ent/ent/issues/3373
* Removes the unnecessary call to template "import/types" since it was just creating an empty line.
=> entgql: Fix duplicate import present in `gql_where_input.go`

entgql/internal/todo/ent/gql_collection.go, entgql/internal/todo/todo_test.go, entgql/internal/todofed/ent/gql_collection.go, entgql/internal/todogotype/ent/gql_collection.go, entgql/internal/todopulid/ent/gql_collection.go, entgql/internal/todouuid/ent/gql_collection.go, entgql/schema.go, entgql/template.go, entgql/template/collection.tmpl
Note that if the schema was extended, an unrecognized field was queried, entgql skips the fields selection because we cannot determine if a non-selected field is used in custom resolvers.
Wait with the review until I add tests to this PR.
=> entgql: add support for query fields selection

entgql/internal/todo/ent/gql_pagination.go, entgql/internal/todogotype/ent/gql_pagination.go, entgql/internal/todopulid/ent/gql_pagination.go, entgql/internal/todouuid/ent/gql_pagination.go, entgql/template/pagination.tmpl
According to https://github.com/ent/ent/issues/3601, I've found this error too when my table's name starts with 'O'. 
It seems variables' name are conflicting; the argument of toCursor function and the one for iterating through p.order.
I've renamed the variable for iterating through p.order to 'po' in a template.
=> fix: rename variable when iterating through p.order in toCursor template

entoas/extension.go, entoas/generator.go
Introduce a new configuration option AllowClientUUIDs to the entoas package. When enabled, it allows the inclusion of the "id" field in the payload of POST requests for entity creation. This enables the clients to supply UUIDs for primary keys, thereby ensuring idempotency.
=> entoas: add option to AllowClientUUIDs for client supplied 'id' in POSTs

entgql/internal/todo/ent/gql_collection.go, entgql/internal/todo/ent/gql_node.go, entgql/internal/todo/ent/gql_pagination.go, entgql/internal/todo/todo_test.go, entgql/internal/todofed/ent/gql_collection.go, entgql/internal/todofed/ent/gql_node.go, entgql/internal/todofed/ent/gql_pagination.go, entgql/internal/todogotype/ent/gql_collection.go, entgql/internal/todogotype/ent/gql_node.go, entgql/internal/todogotype/ent/gql_pagination.go, entgql/internal/todopulid/ent/gql_collection.go, entgql/internal/todopulid/ent/gql_node.go, entgql/internal/todopulid/ent/gql_pagination.go, entgql/internal/todouuid/ent/gql_collection.go, entgql/internal/todouuid/ent/gql_node.go, entgql/internal/todouuid/ent/gql_pagination.go, entgql/pagination.go, entgql/template/collection.tmpl, entgql/template/node.tmpl, entgql/template/pagination.tmpl
No need to limit per node, when a single node is returned in a path.
I can't share the query publicly, but out internal queries were improved from 400ms to 15ms (on MySQL 8.3).
=> entgql: avoid using cte queries for single node paths

entgql/internal/todo/ent/gql_pagination.go, entgql/internal/todogotype/ent/gql_pagination.go, entgql/internal/todopulid/ent/gql_pagination.go, entgql/internal/todouuid/ent/gql_pagination.go, entgql/template/pagination.tmpl
Improves variable name collision avoidance in the `toCursor` method of the pager types in the `gql_pagination` template by suffixing all hard-coded variables names with an underscore.
Address the issue that was the target of #488 and #538. PR #538 fixed the issue for types that start with "O" but broke it for types that start with "Po" (e.g. "Post") or that are two words with the initials "PO" (e.g. "PostOffice"). The issue is also present for types that have the initials "CS" (e.g. "CourseSection"). My fix here puts an underscore as a suffix on all the internal variables so that variable name collision is not possible.
It might be better to opt out of dynamic variables for the argument altogether or updating the variable name generator to accept more context about names to avoid, but …
=> entgql: improve var name collision avoidance in toCursor

ci/action.yaml
If you use ent/contrib/ci action in GitHub Actions as follows, you will see a warning message.
```yaml
jobs:
codegen-check:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v4
- uses: actions/setup-go@v5
with:
go-version: 1.22
- uses: ent/contrib/ci@master
```
This message is shown due to the use of deprecated node16 actions. Updating actions/github-script from v6 to v7 will resolve this issue. cf.) https://github.com/actions/github-script/releases/tag/v7.0.0
=> ci: use node20 actions because node16 actions are deprecated

entgql/schema.go
Before this change, when SkipMutationCreateInput was annotated on an entity, the CreateXxxInput was omitted from the `gql_mutation_input.go` generated types, but still included in the `ent.graphql` generated schema. The same was true for SkipMutationUpdateInput.
To work around this, you could use entgql.Mutations to select only the ones you want generated. But, according to the annotation comments, using SkipMutationCreateInput in this way should be supported.
For example, this works as expected:
```go
func (File) Annotations() []schema.Annotation {
return []schema.Annotation{
entgql.Mutations(entgql.MutationUpdate()),
}
}
```
While this does not (it still generates CreateFileInput in ent.graphql):
```go
func (File) Annotations() []schema.Annotation {
return []schema.Annotation{ …
```
=> entgql: support SkipMutationCreateInput (and update) on entity

entgql/internal/todo/ent/gql_collection.go, entgql/internal/todofed/ent/gql_collection.go, entgql/internal/todogotype/ent/gql_collection.go, entgql/internal/todopulid/ent/gql_collection.go, entgql/internal/todouuid/ent/gql_collection.go, entgql/template/collection.tmpl
GQLGen changed its behavior in https://github.com/99designs/gqlgen/pull/3162 to return a zero value for `null`.
Which causes `first` / `last` to receive the 0 value, and fail the check for supplying both `first` and `last`
=> entgql: fixed zero value on `first`/`last` when receive `null` input

entgql/template/mutation_input.tmpl
Refer: https://github.com/ent/ent/pull/4281
I am building a Media Extension need to set Fields on e.g PostMutation via `saas/gen/ent/gql_mutation_input.go`
So instead of copying the whole template file and overriding, we should be able to override within the default template from the vendor directory.
and also this way multiple custom extensions can add additional fields and make it modular.
=> ability to add additonal fields and funcs to mutation input
